server:
  port: 9970

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jasper
    password: jasper1234
    url: jdbc:mysql://localhost:3306/jasper_test_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    show_sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true